<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 3/23/16
 * Time: 1:09 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccesorioRepository extends EntityRepository
{
}
