<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 8/19/16
 * Time: 3:41 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{

}