<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 4/4/16
 * Time: 12:31 a.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoRepository extends EntityRepository
{
    private $doctrineManager;

    public function setDoctrineManager($_doctrineManager)
    {
        $this->doctrineManager = $_doctrineManager;
    }

    public function findByOwner($idUsuario)
    {
        $resultset = $this->findBy(array('id_usuario' => $idUsuario));

        return $resultset;
    }

    public function findByListaContacto($idListaContacto)
    {
        $connection = $this->doctrineManager->getConnection();

        $statement = $connection->prepare("
          SELECT c.*
          FROM contacto_listacontacto clc
          INNER JOIN contacto c ON clc.id_contacto = c.id
          WHERE clc.id_listacontacto = :idListaContacto AND c.activo = true"
        );
        $statement->bindValue('idListaContacto', $idListaContacto);
        $statement->execute();

        $resultset = $statement->fetchAll();

        return $resultset;
    }
}