<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 8/14/16
 * Time: 12:40 a.m.
 */


namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuartoServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuartoServicioRepository extends EntityRepository
{
}
