<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 8/4/16
 * Time: 2:55 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GerenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GerenciaRepository extends EntityRepository
{

}
