<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 8/1/16
 * Time: 10:13 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenRepository extends EntityRepository
{
}