<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 8/17/16
 * Time: 1:43 a.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenActividadRepository extends EntityRepository
{

}