<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 3/24/16
 * Time: 7:43 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipioRepository extends EntityRepository
{
    public function findByEstado($idEstado)
    {
        return $this->findBy(array('estado' => $idEstado, 'activo' => true));
    }

    public function buscarPorNombre($nombre)
    {
        $resultset = $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM AppBundle:Municipio m WHERE m.nombre LIKE :nombre'
            )
            ->setParameter('nombre', '%' . $nombre . '%')->getResult();

        return $resultset;
    }
}