<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 5/23/16
 * Time: 12:11 a.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaRepository extends EntityRepository
{
    public function findByOwnerCount($idUsuario)
    {
        $count = $this->getEntityManager()
            ->createQuery(
                'SELECT count(n.idNoticia) FROM AppBundle:Noticia n WHERE n.id_usuario = :idUsuario'
            )->setParameter('idUsuario', $idUsuario)->getSingleScalarResult();

        return $count;
    }
}