<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 8/14/16
 * Time: 12:41 a.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoclimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoClimaRepository extends EntityRepository
{
}
