<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Comision extends \AppBundle\Entity\Comision implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'asesor', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'comparte', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'inmueble', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'operacioninmueble', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'cliente', 'monto', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'propiedadexterna', 'comision', 'comisionoficina', 'comisionasesor', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'activo');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'asesor', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'comparte', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'inmueble', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'operacioninmueble', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'cliente', 'monto', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'propiedadexterna', 'comision', 'comisionoficina', 'comisionasesor', '' . "\0" . 'AppBundle\\Entity\\Comision' . "\0" . 'activo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Comision $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setComparte($comparte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComparte', array($comparte));

        return parent::setComparte($comparte);
    }

    /**
     * {@inheritDoc}
     */
    public function getComparte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComparte', array());

        return parent::getComparte();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente($cliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', array($cliente));

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto($monto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', array($monto));

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', array());

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropiedadexterna($propiedadexterna)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropiedadexterna', array($propiedadexterna));

        return parent::setPropiedadexterna($propiedadexterna);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropiedadexterna()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropiedadexterna', array());

        return parent::getPropiedadexterna();
    }

    /**
     * {@inheritDoc}
     */
    public function setComision($comision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComision', array($comision));

        return parent::setComision($comision);
    }

    /**
     * {@inheritDoc}
     */
    public function getComision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComision', array());

        return parent::getComision();
    }

    /**
     * {@inheritDoc}
     */
    public function setComisionoficina($comisionoficina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComisionoficina', array($comisionoficina));

        return parent::setComisionoficina($comisionoficina);
    }

    /**
     * {@inheritDoc}
     */
    public function getComisionoficina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComisionoficina', array());

        return parent::getComisionoficina();
    }

    /**
     * {@inheritDoc}
     */
    public function setComisionasesor($comisionasesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComisionasesor', array($comisionasesor));

        return parent::setComisionasesor($comisionasesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getComisionasesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComisionasesor', array());

        return parent::getComisionasesor();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\AppBundle\Entity\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setInmueble(\AppBundle\Entity\Inmueble $inmueble)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInmueble', array($inmueble));

        return parent::setInmueble($inmueble);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmueble()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmueble', array());

        return parent::getInmueble();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperacioninmueble(\AppBundle\Entity\OperacionInmueble $operacioninmueble)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperacioninmueble', array($operacioninmueble));

        return parent::setOperacioninmueble($operacioninmueble);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperacioninmueble()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperacioninmueble', array());

        return parent::getOperacioninmueble();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsesor(\AppBundle\Entity\Usuario $asesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsesor', array($asesor));

        return parent::setAsesor($asesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsesor', array());

        return parent::getAsesor();
    }

}
