<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Rotulo extends \AppBundle\Entity\Rotulo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'asesor', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'accion', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'elementos', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'tamano', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'inmueble', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'activo');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'asesor', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'accion', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'elementos', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'tamano', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'inmueble', '' . "\0" . 'AppBundle\\Entity\\Rotulo' . "\0" . 'activo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Rotulo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\AppBundle\Entity\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccion(\AppBundle\Entity\RotuloAccion $accion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccion', array($accion));

        return parent::setAccion($accion);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccion', array());

        return parent::getAccion();
    }

    /**
     * {@inheritDoc}
     */
    public function addElemento(\AppBundle\Entity\RotuloElemento $elementos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addElemento', array($elementos));

        return parent::addElemento($elementos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeElemento(\AppBundle\Entity\RotuloElemento $elementos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeElemento', array($elementos));

        return parent::removeElemento($elementos);
    }

    /**
     * {@inheritDoc}
     */
    public function getElementos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElementos', array());

        return parent::getElementos();
    }

    /**
     * {@inheritDoc}
     */
    public function setTamano(\AppBundle\Entity\RotuloTamano $tamano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTamano', array($tamano));

        return parent::setTamano($tamano);
    }

    /**
     * {@inheritDoc}
     */
    public function getTamano()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTamano', array());

        return parent::getTamano();
    }

    /**
     * {@inheritDoc}
     */
    public function setInmueble(\AppBundle\Entity\Inmueble $inmueble)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInmueble', array($inmueble));

        return parent::setInmueble($inmueble);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmueble()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmueble', array());

        return parent::getInmueble();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsesor(\AppBundle\Entity\Usuario $asesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsesor', array($asesor));

        return parent::setAsesor($asesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsesor', array());

        return parent::getAsesor();
    }

}
