<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tarea extends \AppBundle\Entity\Tarea implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'idTarea', 'id_usuario', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'fecha', 'id_accion', 'id_prospecto', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'propiedad', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'comentarios', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'agregarmicalendario', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'indexSelectedAsesor');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'idTarea', 'id_usuario', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'fecha', 'id_accion', 'id_prospecto', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'propiedad', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'comentarios', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'agregarmicalendario', '' . "\0" . 'AppBundle\\Entity\\Tarea' . "\0" . 'indexSelectedAsesor');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tarea $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAgregarmicalendario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgregarmicalendario', array());

        return parent::getAgregarmicalendario();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgregarmicalendario($agregarmicalendario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgregarmicalendario', array($agregarmicalendario));

        return parent::setAgregarmicalendario($agregarmicalendario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTarea()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdTarea();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTarea', array());

        return parent::getIdTarea();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropiedad($propiedad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropiedad', array($propiedad));

        return parent::setPropiedad($propiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropiedad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropiedad', array());

        return parent::getPropiedad();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentarios($comentarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentarios', array($comentarios));

        return parent::setComentarios($comentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentarios', array());

        return parent::getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(\AppBundle\Entity\Usuario $idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAccion(\AppBundle\Entity\Accion $idAccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAccion', array($idAccion));

        return parent::setIdAccion($idAccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAccion', array());

        return parent::getIdAccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProspecto(\AppBundle\Entity\Prospecto $idProspecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProspecto', array($idProspecto));

        return parent::setIdProspecto($idProspecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProspecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProspecto', array());

        return parent::getIdProspecto();
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexSelectedAsesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexSelectedAsesor', array());

        return parent::getIndexSelectedAsesor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexSelectedAsesor($indexSelectedAsesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexSelectedAsesor', array($indexSelectedAsesor));

        return parent::setIndexSelectedAsesor($indexSelectedAsesor);
    }

}
