<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AsesorPermiso extends \AppBundle\Entity\AsesorPermiso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'altapropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'editarpropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'inactivarpropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'eliminarpropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'notificaraltapropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'duplicarprospectos', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'publicarsolocondatospropietario', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'destacarpropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'activo');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'altapropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'editarpropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'inactivarpropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'eliminarpropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'notificaraltapropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'duplicarprospectos', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'publicarsolocondatospropietario', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'destacarpropiedad', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\AsesorPermiso' . "\0" . 'activo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AsesorPermiso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAltapropiedad($altapropiedad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAltapropiedad', array($altapropiedad));

        return parent::setAltapropiedad($altapropiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function getAltapropiedad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAltapropiedad', array());

        return parent::getAltapropiedad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditarpropiedad($editarpropiedad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditarpropiedad', array($editarpropiedad));

        return parent::setEditarpropiedad($editarpropiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditarpropiedad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditarpropiedad', array());

        return parent::getEditarpropiedad();
    }

    /**
     * {@inheritDoc}
     */
    public function setInactivarpropiedad($inactivarpropiedad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInactivarpropiedad', array($inactivarpropiedad));

        return parent::setInactivarpropiedad($inactivarpropiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function getInactivarpropiedad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInactivarpropiedad', array());

        return parent::getInactivarpropiedad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEliminarpropiedad($eliminarpropiedad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEliminarpropiedad', array($eliminarpropiedad));

        return parent::setEliminarpropiedad($eliminarpropiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEliminarpropiedad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEliminarpropiedad', array());

        return parent::getEliminarpropiedad();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificaraltapropiedad($notificaraltapropiedad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificaraltapropiedad', array($notificaraltapropiedad));

        return parent::setNotificaraltapropiedad($notificaraltapropiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificaraltapropiedad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificaraltapropiedad', array());

        return parent::getNotificaraltapropiedad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuplicarprospectos($duplicarprospectos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuplicarprospectos', array($duplicarprospectos));

        return parent::setDuplicarprospectos($duplicarprospectos);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuplicarprospectos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuplicarprospectos', array());

        return parent::getDuplicarprospectos();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicarsolocondatospropietario($publicarsolocondatospropietario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicarsolocondatospropietario', array($publicarsolocondatospropietario));

        return parent::setPublicarsolocondatospropietario($publicarsolocondatospropietario);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicarsolocondatospropietario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicarsolocondatospropietario', array());

        return parent::getPublicarsolocondatospropietario();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\AppBundle\Entity\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestacarpropiedad($destacarpropiedad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestacarpropiedad', array($destacarpropiedad));

        return parent::setDestacarpropiedad($destacarpropiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestacarpropiedad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestacarpropiedad', array());

        return parent::getDestacarpropiedad();
    }

}
