<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 4/23/16
 * Time: 8:56 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CaracteristicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristicaRepository extends EntityRepository
{

}