<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 6/16/16
 * Time: 4:16 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaInmuebleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaInmuebleRepository extends EntityRepository
{
}
