<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 3/24/16
 * Time: 7:45 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ColoniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColoniaRepository extends EntityRepository
{
    public function findByMunicipio($idMunicipio)
    {
        return $this->findBy(array('municipio' => $idMunicipio));
    }
}