<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 4/4/16
 * Time: 12:31 a.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoRepository extends EntityRepository
{
    public function findByOwner($idUsuario)
    {
        $resultset = $this->findBy(array('id_usuario' => $idUsuario));

        return $resultset;
    }
}