<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 4/3/16
 * Time: 11:49 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ColoniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaContactoRepository extends EntityRepository
{
    public function findByOwner($idUsuario)
    {
        $resultset = $this->findBy(array('id_usuario' => $idUsuario));

        return $resultset;
    }
}