<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 6/16/16
 * Time: 6:38 a.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MensajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajeRepository extends EntityRepository
{

}