<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prospecto extends \AppBundle\Entity\Prospecto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'idProspecto', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'nombreCompleto', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'email', 'id_estado', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'ciudad', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'telefonoMovil', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'presupuesto', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'observaciones', 'id_usuario', 'id_canal_captacion', 'id_estatus_avance', 'id_tipo_prospecto', 'documentos', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'activo');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'idProspecto', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'nombreCompleto', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'email', 'id_estado', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'ciudad', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'telefonoMovil', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'presupuesto', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'observaciones', 'id_usuario', 'id_canal_captacion', 'id_estatus_avance', 'id_tipo_prospecto', 'documentos', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Prospecto' . "\0" . 'activo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Prospecto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdProspecto()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdProspecto();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProspecto', array());

        return parent::getIdProspecto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCompleto', array());

        return parent::getNombreCompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', array($apellidos));

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', array());

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad($ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', array($ciudad));

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', array());

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoMovil($telefonoMovil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoMovil', array($telefonoMovil));

        return parent::setTelefonoMovil($telefonoMovil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoMovil', array());

        return parent::getTelefonoMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresupuesto($presupuesto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresupuesto', array($presupuesto));

        return parent::setPresupuesto($presupuesto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresupuesto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresupuesto', array());

        return parent::getPresupuesto();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstado(\AppBundle\Entity\Estado $idEstado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstado', array($idEstado));

        return parent::setIdEstado($idEstado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstado', array());

        return parent::getIdEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(\AppBundle\Entity\Usuario $idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCanalCaptacion(\AppBundle\Entity\CanalCaptacion $idCanalCaptacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCanalCaptacion', array($idCanalCaptacion));

        return parent::setIdCanalCaptacion($idCanalCaptacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCanalCaptacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCanalCaptacion', array());

        return parent::getIdCanalCaptacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstatusAvance(\AppBundle\Entity\EstatusAvance $idEstatusAvance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstatusAvance', array($idEstatusAvance));

        return parent::setIdEstatusAvance($idEstatusAvance);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstatusAvance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstatusAvance', array());

        return parent::getIdEstatusAvance();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipoProspecto(\AppBundle\Entity\TipoProspecto $idTipoProspecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipoProspecto', array($idTipoProspecto));

        return parent::setIdTipoProspecto($idTipoProspecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipoProspecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipoProspecto', array());

        return parent::getIdTipoProspecto();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocumento(\AppBundle\Entity\Documento $documentos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocumento', array($documentos));

        return parent::addDocumento($documentos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocumento(\AppBundle\Entity\Documento $documentos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocumento', array($documentos));

        return parent::removeDocumento($documentos);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentos', array());

        return parent::getDocumentos();
    }

}
