# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        pd_db_provider:
            entity:
                class: AppBundle:Usuario
                property: email
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                  login_path: login
                  check_path: login
            logout:
                path:   /logout
                target: /

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: /panel_principal, roles: 'ROLE_AGENTE_INMOBILIARIO' }
        - { path: /panel_prospecto, roles: 'ROLE_AGENTE_INMOBILIARIO' }
        - { path: /prospecto, roles: 'ROLE_AGENTE_INMOBILIARIO' }
        - { path: /contacto, roles: 'ROLE_AGENTE_INMOBILIARIO' }
        - { path: /listacontacto, roles: 'ROLE_AGENTE_INMOBILIARIO' }
        - { path: /colaborador, roles: 'ROLE_AGENTE_INMOBILIARIO' }
        - { path: /inmuebleimagen, roles: 'ROLE_AGENTE_INMOBILIARIO' }

        - { path: /mensaje/index, roles: 'ROLE_CLIENTE' }
        - { path: /mensaje/new, roles: 'ROLE_CLIENTE' }

