<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \AppBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'telefono2', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'celular', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'activo', 'rol', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'colaboradores', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'idUsuarioPadre', 'pathFoto', 'urlFoto', 'fileFoto', 'pathLogo', 'urlLogo', 'fileLogo', 'websitekey', 'facebookToken');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'telefono2', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'celular', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'activo', 'rol', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'colaboradores', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'idUsuarioPadre', 'pathFoto', 'urlFoto', 'fileFoto', 'pathLogo', 'urlLogo', 'fileLogo', 'websitekey', 'facebookToken');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuarioPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuarioPadre', array());

        return parent::getIdUsuarioPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuarioPadre($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuarioPadre', array($id));

        return parent::setIdUsuarioPadre($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa($empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookToken($facebookToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookToken', array($facebookToken));

        return parent::setFacebookToken($facebookToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookToken', array());

        return parent::getFacebookToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRol(\AppBundle\Entity\Rol $rol = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRol', array($rol));

        return parent::setRol($rol);
    }

    /**
     * {@inheritDoc}
     */
    public function getRol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRol', array());

        return parent::getRol();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function isEqualTo(\Symfony\Component\Security\Core\User\UserInterface $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEqualTo', array($user));

        return parent::isEqualTo($user);
    }

    /**
     * {@inheritDoc}
     */
    public function addColaborador(\AppBundle\Entity\Usuario $colaborador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addColaborador', array($colaborador));

        return parent::addColaborador($colaborador);
    }

    /**
     * {@inheritDoc}
     */
    public function removeZona(\AppBundle\Entity\Usuario $colaboradores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeZona', array($colaboradores));

        return parent::removeZona($colaboradores);
    }

    /**
     * {@inheritDoc}
     */
    public function getColaboradores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColaboradores', array());

        return parent::getColaboradores();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsitekey($websitekey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsitekey', array($websitekey));

        return parent::setWebsitekey($websitekey);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsitekey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsitekey', array());

        return parent::getWebsitekey();
    }

    /**
     * {@inheritDoc}
     */
    public function setPathFoto($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathFoto', array($path));

        return parent::setPathFoto($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPathFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPathFoto', array());

        return parent::getPathFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setURLFoto($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setURLFoto', array($url));

        return parent::setURLFoto($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getURLFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getURLFoto', array());

        return parent::getURLFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileFoto($fileFoto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileFoto', array($fileFoto));

        return parent::setFileFoto($fileFoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileFoto', array());

        return parent::getFileFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function uploadFoto($nombrearchivo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'uploadFoto', array($nombrearchivo));

        return parent::uploadFoto($nombrearchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePathFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePathFoto', array());

        return parent::getAbsolutePathFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPathFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPathFoto', array());

        return parent::getWebPathFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPathLogo($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathLogo', array($path));

        return parent::setPathLogo($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPathLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPathLogo', array());

        return parent::getPathLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setURLLogo($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setURLLogo', array($url));

        return parent::setURLLogo($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getURLLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getURLLogo', array());

        return parent::getURLLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileLogo($fileLogo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileLogo', array($fileLogo));

        return parent::setFileLogo($fileLogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileLogo', array());

        return parent::getFileLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function uploadLogo($nombrearchivo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'uploadLogo', array($nombrearchivo));

        return parent::uploadLogo($nombrearchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePathLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePathLogo', array());

        return parent::getAbsolutePathLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPathLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPathLogo', array());

        return parent::getWebPathLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono2($telefono2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono2', array($telefono2));

        return parent::setTelefono2($telefono2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono2', array());

        return parent::getTelefono2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCelular($celular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCelular', array($celular));

        return parent::setCelular($celular);
    }

    /**
     * {@inheritDoc}
     */
    public function getCelular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelular', array());

        return parent::getCelular();
    }

    /**
     * {@inheritDoc}
     */
    public function addColaboradore(\AppBundle\Entity\Usuario $colaboradores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addColaboradore', array($colaboradores));

        return parent::addColaboradore($colaboradores);
    }

    /**
     * {@inheritDoc}
     */
    public function removeColaboradore(\AppBundle\Entity\Usuario $colaboradores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeColaboradore', array($colaboradores));

        return parent::removeColaboradore($colaboradores);
    }

}
