<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mensaje extends \AppBundle\Entity\Mensaje implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'idMensaje', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'id_usuario', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'destinoemail', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'titulo', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'texto', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'leido', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'inmuebles', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'tipoMensaje', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'id_listacontacto');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'idMensaje', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'id_usuario', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'destinoemail', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'titulo', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'texto', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'leido', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'inmuebles', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'tipoMensaje', '' . "\0" . 'AppBundle\\Entity\\Mensaje' . "\0" . 'id_listacontacto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mensaje $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdMensaje()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdMensaje();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMensaje', array());

        return parent::getIdMensaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestinoemail($destinoemail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinoemail', array($destinoemail));

        return parent::setDestinoemail($destinoemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinoemail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinoemail', array());

        return parent::getDestinoemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeido($leido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeido', array($leido));

        return parent::setLeido($leido);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeido', array());

        return parent::getLeido();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexto($texto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexto', array($texto));

        return parent::setTexto($texto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTexto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexto', array());

        return parent::getTexto();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoMensaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoMensaje', array());

        return parent::getTipoMensaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoMensaje($tipoMensaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoMensaje', array($tipoMensaje));

        return parent::setTipoMensaje($tipoMensaje);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(\AppBundle\Entity\Usuario $idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function addInmueble(\AppBundle\Entity\Inmueble $inmuebles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInmueble', array($inmuebles));

        return parent::addInmueble($inmuebles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInmueble(\AppBundle\Entity\Inmueble $inmuebles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInmueble', array($inmuebles));

        return parent::removeInmueble($inmuebles);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmuebles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmuebles', array());

        return parent::getInmuebles();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdListacontacto(\AppBundle\Entity\ListaContacto $idListaContacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdListacontacto', array($idListaContacto));

        return parent::setIdListacontacto($idListaContacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdListacontacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdListacontacto', array());

        return parent::getIdListacontacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

}
