<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Solicitud extends \AppBundle\Entity\Solicitud implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'idSolicitud', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'id_usuario', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'id_tipo_inmueble', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'id_operacion_inmueble', 'id_estado', 'id_municipio', 'id_colonia', 'id_moneda', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'fechaCreacion', 'precio', 'preciomax', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'metrosconstruccion', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'metrosconstruccionmax', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'metrosterreno', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'metrosterrenomax', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'caracteristicas', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'descripcion');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'idSolicitud', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'id_usuario', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'id_tipo_inmueble', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'id_operacion_inmueble', 'id_estado', 'id_municipio', 'id_colonia', 'id_moneda', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'fechaCreacion', 'precio', 'preciomax', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'metrosconstruccion', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'metrosconstruccionmax', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'metrosterreno', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'metrosterrenomax', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'caracteristicas', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Solicitud' . "\0" . 'descripcion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Solicitud $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(\AppBundle\Entity\Usuario $idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipoInmueble(\AppBundle\Entity\TipoInmueble $idTipoInmueble)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipoInmueble', array($idTipoInmueble));

        return parent::setIdTipoInmueble($idTipoInmueble);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipoInmueble()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipoInmueble', array());

        return parent::getIdTipoInmueble();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdOperacionInmueble(\AppBundle\Entity\OperacionInmueble $idOperacionInmueble)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdOperacionInmueble', array($idOperacionInmueble));

        return parent::setIdOperacionInmueble($idOperacionInmueble);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdOperacionInmueble()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOperacionInmueble', array());

        return parent::getIdOperacionInmueble();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstado(\AppBundle\Entity\Estado $idEstado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstado', array($idEstado));

        return parent::setIdEstado($idEstado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstado', array());

        return parent::getIdEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMunicipio(\AppBundle\Entity\Municipio $idMunicipio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMunicipio', array($idMunicipio));

        return parent::setIdMunicipio($idMunicipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMunicipio', array());

        return parent::getIdMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdColonia(\AppBundle\Entity\Colonia $idColonia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdColonia', array($idColonia));

        return parent::setIdColonia($idColonia);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdColonia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdColonia', array());

        return parent::getIdColonia();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdInmueble()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdInmueble', array());

        return parent::getIdInmueble();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMoneda(\AppBundle\Entity\Moneda $idMoneda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMoneda', array($idMoneda));

        return parent::setIdMoneda($idMoneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMoneda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMoneda', array());

        return parent::getIdMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', array($precio));

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', array());

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreciomax($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreciomax', array($precio));

        return parent::setPreciomax($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreciomax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreciomax', array());

        return parent::getPreciomax();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetrosconstruccion($metrosconstruccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetrosconstruccion', array($metrosconstruccion));

        return parent::setMetrosconstruccion($metrosconstruccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetrosconstruccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetrosconstruccion', array());

        return parent::getMetrosconstruccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetrosterrenomax($metrosterreno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetrosterrenomax', array($metrosterreno));

        return parent::setMetrosterrenomax($metrosterreno);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetrosterrenomax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetrosterrenomax', array());

        return parent::getMetrosterrenomax();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetrosterreno($metrosterreno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetrosterreno', array($metrosterreno));

        return parent::setMetrosterreno($metrosterreno);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetrosterreno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetrosterreno', array());

        return parent::getMetrosterreno();
    }

    /**
     * {@inheritDoc}
     */
    public function addCaracteristica(\AppBundle\Entity\Caracteristica $caracteristicas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCaracteristica', array($caracteristicas));

        return parent::addCaracteristica($caracteristicas);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCaracteristica(\AppBundle\Entity\Caracteristica $caracteristicas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCaracteristica', array($caracteristicas));

        return parent::removeCaracteristica($caracteristicas);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaracteristicas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaracteristicas', array());

        return parent::getCaracteristicas();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSolicitud()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdSolicitud();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSolicitud', array());

        return parent::getIdSolicitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetrosconstruccionmax($metrosconstruccionmax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetrosconstruccionmax', array($metrosconstruccionmax));

        return parent::setMetrosconstruccionmax($metrosconstruccionmax);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetrosconstruccionmax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetrosconstruccionmax', array());

        return parent::getMetrosconstruccionmax();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

}
